### ISSUE TITLE
"YACL-style GUI Tooltips" feature is missing

### ISSUE THREAD

**Issue by Tapacywka** [1foxy2/BetterTooltips#1]
The original mod has this feature, which is also listed on the CurseForge page of this fork.
Btw, this option is not in the game. It is not in the mod settings menu, nor in the config file itself.

![image](https://github.com/user-attachments/assets/8bb3db60-711b-4f2c-9f7b-e12a806800dd)

If anything, I have YACL for NeoForge 1.21.1 installed.

**Comment by 1foxy2** [comment]
accidently deleted it with yacl config (neoforge has it own config system)
